"""Add tag field to QAEntry model

Revision ID: ae2580394614
Revises: 8107d8974a95
Create Date: 2024-02-06 16:55:38.778441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2580394614'
down_revision = '8107d8974a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_entry', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
